name: asdf-quarkus tests
on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:

#  plugin-linting:
#    runs-on: ubuntu-latest
#    env:
#      TERM: dumb
#    steps:
#      - uses: actions/checkout@v2
#      - uses: mstksg/get-package@v1
#        with:
#          apt-get: shellcheck
#      - name: Run ShellCheck
#        run: |
#          shellcheck -V
#          shellcheck ./bin/*

  plugin-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
#          - ubuntu-latest
    env:
      TERM: dumb
      GITHUB_API_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - run: java -version
      - run: |
          env | sort
          which java
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v2
        with:
          command: quarkus version
