name: asdf-java Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macOS-latest']
    env:
      TERM: dumb
    steps:
      - uses: actions/checkout@v2
      - uses: mstksg/get-package@v1
        with:
          brew: bash coreutils shellcheck
          apt-get: shellcheck
      - name: Run ShellCheck
        run: |
          shellcheck -V
          shellcheck ./bin/*
      - name: Install asdf
        uses: actions/checkout@v2
        with:
          repository: asdf-vm/asdf
          path: asdf
      - name: Install java
        run: |
          . asdf/asdf.sh
          asdf plugin add java
          asdf install java temurin-11.0.20+8
          asdf global java temurin-11.0.20+8
      - name: Run tests
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          . asdf/asdf.sh
          asdf plugin-test quarkus-cli "$GITHUB_WORKSPACE" --asdf-plugin-gitref "$GITHUB_SHA" --asdf-tool-version 3.2.2.Final quarkus -version
