name: asdf-quarkus tests
on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:

  plugin-linting:
    runs-on: ubuntu-latest
    env:
      TERM: dumb
    steps:
      - uses: actions/checkout@v2
      - uses: mstksg/get-package@v1
        with:
          apt-get: shellcheck
      - name: Run ShellCheck
        run: |
          shellcheck -V
          shellcheck ./bin/*

  plugin-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    env:
      TERM: dumb
      GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: install java
        uses: asdf-vm/actions/install@v2
        with:
          tool_versions: "java temurin-11.0.20+8"
      - run: java -version
      - run: asdf plugin-test quarkus-cli "$GITHUB_WORKSPACE" --asdf-plugin-gitref "$GITHUB_SHA" --asdf-tool-version 3.2.2.Final quarkus -version
